let first_name = "Ome Ali";
let last_name = "Shams";
let age = 30;
let dateofbirth= "05/02/2500";
let address = "Pakistan";
console.log('first_name:', first_name); 
console.log('last_name:', last_name);
console.log('age:', age);
console.log('dateofbirth;', dateofbirth );
console.log ('address:', address);